apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hackathon-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
  - http:
      paths:
      - path: /patient
        pathType: Prefix
        backend:
          service:
            name: patient-service
            port:
              number: 3000

      - path: /appointment
        pathType: Prefix
        backend:
          service:
            name: application-service
            port:
              number: 3001

      - path: /order
        pathType: Prefix
        backend:
          service:
            name: order-service
            port:
              number: 8080
