name: GCP CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: ${{ secrets.GCP_REGION }}
  REPO_NAME: hackathon-docker-repo
  CLUSTER_NAME: hackathon-gke

jobs:

  bootstrap:
    name: Bootstrap Terraform Backend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - uses: google-github-actions/setup-gcloud@v2

      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Init (Bootstrap)
        working-directory: terraform/bootstrap
        run: terraform init

      - name: Terraform Apply (Bootstrap)
        working-directory: terraform/bootstrap
        run: terraform apply -auto-approve


  terraform:
    name: Provision Infrastructure
    needs: bootstrap
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - uses: google-github-actions/setup-gcloud@v2

      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve


  build-push-deploy:
    name: Build, Push & Deploy
    needs: terraform
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: gcloud auth configure-docker $REGION-docker.pkg.dev --quiet

      - name: Build & Push Patient
        run: |
          docker build -t $REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/patient-service:latest ./patient-service
          docker push $REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/patient-service:latest

      - name: Build & Push Application
        run: |
          docker build -t $REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/application-service:latest ./application-service
          docker push $REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/application-service:latest

      - name: Build & Push Order
        run: |
          docker build -t $REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/order-service:latest ./order-service
          docker push $REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/order-service:latest

      - name: Get GKE Credentials
        run: |
          gcloud container clusters get-credentials $CLUSTER_NAME \
            --region $REGION \
            --project $PROJECT_ID
            
      - name: Inject Image Registry
        run: |
          REGISTRY=$REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME
          sed -i "s|<YOUR_REGISTRY>|$REGISTRY|g" k8s/*.yaml

      - name: Deploy to GKE
        run: kubectl apply -f k8s/
