name: Terraform Plan - Dev

on:
  push:
    branches: [dev]

permissions:
  id-token: write
  contents: read

env:
  PROJECT_ID: massive-sandbox-477717-k3

jobs:
  terraform-plan-dev:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra/gcp/envs/dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Authenticate to GCP via WIF
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER_DEV }}
          service_account: github-terraform-dev@${{ env.PROJECT_ID }}.iam.gserviceaccount.com
          project_id: ${{ env.PROJECT_ID }}
          audience: ${{ secrets.WIF_PROVIDER_DEV }}
          create_credentials_file: true
          export_environment_variables: true
          token_format: "access_token"

      - name: Terraform Format
        run: terraform fmt -recursive

      - name: Terraform Init
        run: terraform init -backend-config=backend.hcl -input=false

      - name: Terraform Validate
        run: terraform validate -no-color

      - name: Terraform Plan
        run: terraform plan -out=tfplan -input=false -no-color

      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan-dev
          path: infra/gcp/envs/dev/tfplan
